"""Sphinx configuration.

The guide pages are Markdown (MyST); the API reference under ``reference/`` is
generated by autodoc from the package docstrings, which are written in
Sphinx's rST style — that is why the ``:class:`` / ``:mod:`` roles in the
source cross-link for free. Build with ``uv run sphinx-build -W docs docs/_build/html``.
"""

from __future__ import annotations

from importlib.metadata import version as _version
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sphinx.application import Sphinx

project = "robodog-sdk"
author = "Fabian Bahr"
copyright = "2026, Hochschule Esslingen"
release = _version("robodog-sdk")
version = release

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",  # docstrings use Google-style Args:/Returns: sections
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
    "sphinx_design",
    "sphinx_reredirects",
]

# Guide pages link across files with GitHub-style anchors; this makes MyST
# generate them.
myst_heading_anchors = 3
myst_enable_extensions = ["colon_fence", "deflist"]
# ```mermaid fences in the guides become mermaid directives instead of
# (unhighlightable) code blocks.
myst_fence_as_directive = ["mermaid"]

autodoc_member_order = "bysource"
autodoc_preserve_defaults = True
autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pydantic": ("https://docs.pydantic.dev/latest", None),
    # :class:`zenode.Node` and friends resolve into the zenode docs.
    "zenode": ("https://hse-deb-robodog.github.io/zenode/", None),
}

templates_path = []
exclude_patterns = ["_build", "superpowers"]

# Old page URLs → new homes, so links from course material and the stack
# repo's docs keep working.
redirects: dict[str, str] = {
    "driving": "concepts/motion.html",
    "navigation": "concepts/navigation.html",
    "safety": "concepts/safety.html",
    "tracing": "concepts/tracing.html",
    "testing": "guide/07-testing.html",
    "api/index": "../reference/index.html",
    "api/client": "../reference/client.html",
    "api/msgs": "../reference/messages.html",
    "api/contract": "../reference/topics.html",
    "api/testing": "../reference/testing.html",
}

html_theme = "furo"
html_title = f"robodog-sdk {release}"
html_theme_options = {
    "source_repository": "https://github.com/hse-deb-robodog/robodog-sdk",
    "source_branch": "main",
    "source_directory": "docs/",
}

# Strip prompts when copying shell blocks.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True


def _substitute_version(app: Sphinx, docname: str, source: list[str]) -> None:
    source[0] = source[0].replace("%%SDK_VERSION%%", release)


def setup(app: Sphinx) -> None:
    app.connect("source-read", _substitute_version)
